name: workflow on push or PR

on:
  push:
  pull_request:

jobs:
  test:
    name: Test code
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: run tests
        run: npm i && npm run test
